# -*- coding: utf-8 -*-
"""nlp_Day2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wDMMblYMedrZ9p2LFaglzPmAiXzAlga8
"""

!pip install gensim

import gensim

from gensim.models import Word2Vec, KeyedVectors

import gensim.downloader as api
wv = api.load('word2vec-google-news-300')
vec_king= wv['king']

vec_king

wv['man']

wv.most_similar('man')

wv.most_similar('king')

wv.similarity('man','king')

wv.similarity('man','queen')

import os
from os import path
from wordcloud import WordCloud
text="Everybody is a blend of sunlight and darkness"

wordcloud=WordCloud().generate(text)

worscloud= WordCloud(max_font_size=40).generate(text)
plt.figure()
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.show()

